from .. import common
from ..colors import Color
from ..models.board import Board
from ..models.square import Square

board = Board()

board.add_square(common.GO)
board.add_square(Square("Mediterranean Avenue", Color.BROWN))
board.add_square(common.COMMUNITY_CHEST)
board.add_square(Square("Baltic Avenue", Color.BROWN))
board.add_square(common.INCOME_TAX)
board.add_square(Square("Reading Railroad", Color.RAILROAD))
board.add_square(Square("Oriental Avenue", Color.LIGHT_BLUE))
board.add_square(common.CHANCE)
board.add_square(Square("Vermont Avenue", Color.LIGHT_BLUE))
board.add_square(Square("Connecticut Avenue", Color.LIGHT_BLUE))
board.add_square(common.JAIL)
board.add_square(Square("St. Charles Place", Color.PINK))
board.add_square(common.ELECTRIC_COMPANY)
board.add_square(Square("States Avenue", Color.PINK))
board.add_square(Square("Virginia Avenue", Color.PINK))
board.add_square(Square("Pennsylvania Railroad", Color.RAILROAD))
board.add_square(Square("St. James Place", Color.ORANGE))
board.add_square(common.COMMUNITY_CHEST)
board.add_square(Square("Tennessee Avenue", Color.ORANGE))
board.add_square(Square("New York Avenue", Color.ORANGE))
board.add_square(common.FREE_PARKING)
board.add_square(Square("Kentucky Avenue", Color.RED))
board.add_square(common.CHANCE)
board.add_square(Square("Indiana Avenue", Color.RED))
board.add_square(Square("Illinois Avenue", Color.RED))
board.add_square(Square("B. & O. Railroad", Color.RAILROAD))
board.add_square(Square("Atlantic Avenue", Color.YELLOW))
board.add_square(Square("Ventnor Avenue", Color.YELLOW))
board.add_square(common.WATER_WORKS)
board.add_square(Square("Marvin Gardens", Color.YELLOW))
board.add_square(common.TO_JAIL)
board.add_square(Square("Pacific Avenue", Color.GREEN))
board.add_square(Square("North Carolina Avenue", Color.GREEN))
board.add_square(common.COMMUNITY_CHEST)
board.add_square(Square("Pennsylvania Avenue", Color.GREEN))
board.add_square(Square("Short Line", Color.RAILROAD))
board.add_square(common.CHANCE)
board.add_square(Square("Park Place", Color.DARK_BLUE))
board.add_square(common.LUXURY_TAX)
board.add_square(Square("Boardwalk", Color.DARK_BLUE))
